name:                QueueFamilySelect
version:             0.1.0.0
github:              "idgd/QueueFamilySelect"
license:             AGPL-3
author:              "idgd"
maintainer:          ""
copyright:           "2022 idgd"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            A tiny library to choose Vulkan queue families.
category:            Graphics

description:         Please see the README on GitHub at <https://github.com/idgd/QueueFamilySelect#readme>

build-type: Custom
custom-setup:
  dependencies:
    - base >= 4.7 && < 5
    - Cabal
    - process

dependencies:
- base >= 4.7 && < 5
- vector
- vector-algorithms
- QuickCheck
- quickcheck-instances

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  QueueFamilySelect-test:
    main:                Spec.lhs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QueueFamilySelect
